apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: ml
spec:
  selector:
    matchLabels:
      app: ml
      tier: mongo
  template:
    metadata:
      labels:
        app: ml
        tier: mongo
    spec:
      containers:
        - image: mongo
          name: mongo
          # env:
          #   - name: MYSQL_DATABASE
          #     value: wordpress
          #   - name: MYSQL_ROOT_PASSWORD
          #     value: password
          ports:
            - containerPort: 27017
              name: mysql

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: ml
spec:
  ports:
    - port: 27017
  selector:
    app: ml
    tier: mongo

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-np
spec:
  type: NodePort
  ports:
    - port: 27017
      protocol: TCP
      nodePort: 31000
  selector:
    app: ml
    tier: mongo
